export const siteConfig = {
  name: "Life OS",
  title: "Life OS - Cérebro Digital de Código Aberto e Sistema Operacional Pessoal",
  description:
    "Life OS é um segundo cérebro de código aberto e auto-hospedável, com rastreador de hábitos, app de diário, gerenciador de tarefas, planejador de calendário, controle financeiro e sistema de gestão do conhecimento pessoal.",
  author: "karim-coder",
  repositoryUrl: "https://github.com/karim-coder/life-os",
  ogImage:
    "https://raw.githubusercontent.com/karim-coder/life-os/main/public/screenshots/landing.jpg",
  screenshotUrls: [
    "https://raw.githubusercontent.com/karim-coder/life-os/main/public/screenshots/landing.jpg",
    "https://raw.githubusercontent.com/karim-coder/life-os/main/public/screenshots/dashboard.jpeg",
    "https://raw.githubusercontent.com/karim-coder/life-os/main/public/screenshots/brain-graph.jpeg",
    "https://raw.githubusercontent.com/karim-coder/life-os/main/public/screenshots/insight.jpeg",
  ],
  keywords: [
    "Life OS",
    "life operating system",
    "digital brain",
    "second brain",
    "open source second brain",
    "self hosted productivity app",
    "personal operating system",
    "personal knowledge management",
    "PKM",
    "knowledge graph",
    "habit tracker",
    "habit tracker app",
    "open source habit tracker",
    "self hosted habit tracker",
    "daily habit tracker",
    "habit streak tracker",
    "journal app",
    "open source journal app",
    "daily journal app",
    "digital journal",
    "reflection journal",
    "master calendar",
    "calendar planner",
    "daily planner app",
    "task manager",
    "open source task manager",
    "personal task manager",
    "to do app",
    "goal tracker",
    "focus timer",
    "pomodoro timer",
    "finance tracker",
    "personal finance tracker",
    "life dashboard",
    "personal dashboard",
    "productivity dashboard",
    "all in one productivity app",
    "Next.js productivity app",
    "Prisma app",
    "PWA productivity",
  ],
};
